### ISSUE TITLE
Not working in Firefox 77.0.1

### ISSUE THREAD

**Issue by McBobb** [Materie/deviant-download#1]
The code injector you recommended is for chrome, but I only use Firefox (77.0.1), so I tried using the Code Injector addon

https://addons.mozilla.org/en-CA/firefox/addon/codeinjector/#&gid=1&pid=3

I pasted in the Javascript and the CSS using Code Injector, set it to Current Host at DeviantART (www\.deviantart\.com), but I'm not seeing any download buttons appear.

Am I misunderstanding what you mean when you said "Hover the image"? Do you mean hover the cursor over the image in question? If so, that's not working.

Do you mean hover over the specific image you want to download, or hover over the gallery/folder image if you want to download the whole gallery/folder?

**Comment by Materie** [comment]
Okay, I've tested it, and all you need to do is disable the on page load option. The script is setup to wait until page is loaded to do anything, so if you wait to execute it until after the page is loaded, it won't run.
